theme: PaperMod

params:
  ShowPageNums: true
  fancybox: true
  math: true
  comments: true
  tags: true
  assets:
    disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "/favicon/ghost.ico"
    favicon16x16: "/favicon/ghost-16x16.png"
    favicon32x32: "/favicon/ghost-32x32.png"
    apple_touch_icon: "/favicon/ghost-apple-touch-icon.png"
    safari_pinned_tab: "/favicon/ghost-192x192.png"

  # label:
  #   text: "Home"
  #   icon: /apple-touch-icon.png
  #   iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Aiken's Blog
    subtitle: "<!—#*\"//*—%\"\"\" "
    imageUrl: "https://picture-bed-001-1310572365.cos.ap-guangzhou.myqcloud.com/mac/20241129085731.png"
    imageWidth: 150
    imageHeight: 150
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
      - name: About
        url: about

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: github
      url: "https://github.com/AikenH"
    - name: steam
      url: "https://steamcommunity.com/id/AikenH/"
    - name: zhihu
      url: "https://www.zhihu.com/people/Aiken-h"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0
    minMatchCharLength: 1
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content", "description"]

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 40
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30
    - identifier: search
      name: search
      url: /search
      weight: 70
    - identifier: archives
      name: archives
      url: /archives/
      weight: 50
    - identifier: posts
      name: posts
      url: /posts/
      weight: 20
    - identifier: home
      name: home
      url: /
      weight: 10
    - identifier: about
      name: about
      url: /about/
      weight: 60
    - identifier: linklog
      name: linklog
      url: /linklog/
      weight: 80


outputs:
  home:
    - HTML
    - RSS
    - JSON
