theme: PaperMod

params:
  ShowPageNums: true
  fancybox: true
  math: true
  comments: true
  tags: true
  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon/ron.ico"
    favicon16x16: "/favicon/ron-16x16.png"
    favicon32x32: "/favicon/ron-32x32.png"
    apple_touch_icon: "/favicon/ron-apple-touch-icon.png"
    safari_pinned_tab: "/favicon/ron-192x192.png"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Aiken's Blog
    subtitle: "Let's learn and innovate together!"
    imageUrl: "https://avatars.githubusercontent.com/u/23023315?v=4"
    imageWidth: 150
    imageHeight: 150
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
      - name: About
        url: about

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: x
      url: "https://x.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/"
    - name: steam
      url: ""
    - name: zhihu
      url: ""

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 40
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30
    - identifier: search
      name: search
      url: /search
      weight: 70
    - identifier: archives
      name: archives
      url: /archives/
      weight: 50
    - identifier: posts
      name: posts
      url: /posts/
      weight: 20
    - identifier: home
      name: home
      url: /
      weight: 10
    - identifier: about
      name: about
      url: /about/
      weight: 60


outputs:
  home:
    - HTML
    - RSS
    - JSON
